import random

quotes = [
  "\"Everything little thing, is gonna be alright.\" - Bob Marley",
  "\"The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.\" - Confucius",
  "\"You\'re off to great places, today is your day. Your mountain is waiting, so get on your way. - Dr Seuss\"",
  "\"It always seems impossible until it is done.\" - Nelson Mandela",
  "\"Once you replace negative thoughts with positive ones, you’ll start having positive results.\" - Willie Nelson",
  "\"Positive thinking will let you do everything better than negative thinking will.\" - Zig Ziglar",
  "\"In every day, there are 1,440 minutes. That means we have 1,440 daily opportunities to make a positive impact.\" - Les Brown",
  "\"The only time you fail is when you fall down and stay down.\" - Stephen Richards",
  "\"When you are enthusiastic about what you do, you feel this positive energy. It’s very simple.\" - Paul Coelho",
  "\"Winning is fun, but those moments that you can touch someone’s life in a very positive way are better.\" - Tim Howard",
  "\"Virtually nothing is impossible in this world if you just put your mind to it and maintain a positive attitude.\" - Lou Holtz",
  "\"You are never too old to set another goal or dream a new dream.\" - Les Brown",
  "\"The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.\" - Charles Dickens",
  "\"It’s not whether you get knocked down, it’s whether you get up.\" - Vince Lombardi",
  "\"The struggle you’re in today is developing the strength you need tomorrow.\" - Robert Tew",
  "\"The way I see it, if you want the rainbow, you gotta put up with the rain.\" - Dolly Parton",
  "\"Hard work keeps the wrinkles out of the mind and spirit.\" - Helena Rubinstein",
  "\"The difference between ordinary and extraordinary is that little extra.\" - Jimmy Johnson",
  "\"Success is the sum of small efforts repeated day in and day out.\" - Robert Collier",
  "\"When we are open to new possibilities, we find them. Be open and skeptical of everything.\" - Todd Kashan",
  "\"Happiness is the only thing that multiplies when you share it.\" - Albert Schweitzer",
  "\"The happiness of your life depends upon the quality of your thoughts.\" - Marcus Aurelius",
  "\"The good life is a process, not a state of being. It is a direction, not a destination.\" - Carl Rogers",
  "\"Live life to the fullest and focus on the positive.\" - Matt Cameron",
  "\"If you want to achieve greatness stop asking for permission.\" - Anonymous",
  "\"Things work out best for those who make the best of how things work out.\" - John Wooden",
  "\"To live a creative life, we must lose our fear of being wrong.\" - Anonymous",
  "\"Take up one idea. Make that one idea your life--think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.\" - Swami Vivekananda",
  "\"All our dreams can come true if we have the courage to pursue them.\" - Walt Disney",
  "\"Good things come to people who wait, but better things come to those who go out and get them.\" - Anonymous",
  "\"If you do what you always did, you will get what you always got.\" - Anonymous",
  "\"Success is walking from failure to failure with no loss of enthusiasm.\" - Winston Churchill",
  "\"Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.\" - Vaibhav Shah",
  "\"Opportunities don't happen, you create them.\" - Chris Grosser",
  "\"Try not to become a person of success, but rather try to become a person of value.\" - Albert Einstein",
  "\"Great minds discuss ideas; average minds discuss events; small minds discuss people.\" - Eleanor Roosevelt",
  "\"I have not failed. I've just found 10,000 ways that won't work.\" - Thomas A. Edison",
  "\"If you don't value your time, neither will others. Stop giving away your time and talents--start charging for it.\" - Kim Garst",
  "\"A successful person is one who can lay a firm foundation with the bricks others have thrown at them.\" - David Brinkley",
  "\"No one can make you feel inferior without your consent.\" - Eleanor Roosevelt",
  "\"The distance between insanity and genius is measured only by success.\" - Bruce Feirstein",
  "\"If you can't explain it simply, you don't understand it well enough.\" - Albert Einstein",
  "\"Life is not about finding yourself. Life is about creating yourself.\" - Lolly Daskal",
  "\"Innovation distinguishes between a leader and a follower.\" - Steve Jobs",
  "\"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.\" - Ray Goforth",
  "\"I find that the harder I work, the more luck I seem to have.\" - Thomas Jefferson",
  "\"The starting point of all achievement is desire.\" - Napoleon Hill",
  "\"All progress takes place outside the comfort zone.\" - Michael John Bobak",
  "\"Courage is resistance to fear, mastery of fear--not absence of fear.\" - Mark Twain",
  "\"Only put off until tomorrow what you are willing to die having left undone.\" - Pablo Picasso",
  "\"People often say that motivation doesn't last. Well, neither does bathing--that's why we recommend it daily.\" - Zig Ziglar",
  "\"We become what we think about most of the time, and that's the strangest secret.\" - Earl Nightingale",
  "\"Too many of us are not living our dreams because we are living our fears.\" - Les Brown",
  "\"I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.\" - Martha Stewart",
  "\"Success is liking yourself, liking what you do, and liking how you do it.\" - Maya Angelou",
  "\"People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.\" - Tony Robbins",
  "\"The successful warrior is the average man, with laser-like focus.\" - Bruce Lee",
  "\"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.\" - Dale Carnegie",
  "\"Don't let the fear of losing be greater than the excitement of winning.\" - Robert Kiyosaki",
  "\"If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!\" - T. Harv Eker",
  "\"You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something--your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.\" - Steve Jobs",
  "\"The number one reason people fail in life is because they listen to their friends, family, and neighbors.\" - Napoleon Hill",
  "\"The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them.\" - Denis Waitley",
  "\"Success does not consist in never making mistakes but in never making the same one a second time.\" - George Bernard Shaw",
  "\"You must expect great things of yourself before you can do them.\" - Michael Jordan",
  "\"Motivation is what gets you started. Habit is what keeps you going.\" - Jim Ryun",
  "\"People rarely succeed unless they have fun in what they are doing.\" - Dale Carnegie",
  "\"Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.\" - Francis Chan",
  "\"You've got to get up every morning with determination if you're going to go to bed with satisfaction.\" - George Lorimer",
  "\"Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.\" - Wayne Dyer",
  "\"To accomplish great things, we must not only act, but also dream, not only plan, but also believe.\" - Anatole France",
  "\"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.\" - Dale Carnegie",
  "\"You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.\" - Booker T. Washington",
  "\"It is better to fail in originality than to succeed in imitation.\" - Herman Melville",
  "\"What would you do if you weren't afraid?\" - Spencer Johnson",
  "\"A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done.\" - Vince Lombardi",
  "\"Some people want it to happen, some people wish it would happen, others make it happen.\" - Michael Jordan",
  "\"The man on top of the mountain didn’t fall there.\" - Vince Lombardi",
  "\"Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose. You are already naked. There is no reason not to follow your heart.\" - Steve Jobs",
  "\"Make it work.\" - Tim Gunn",
  "\"Do more.\" - Casey Neistat",
  "\"Stay hungry.\" - Arnold Schwarzenegger",
  "\"Never let go of that fiery sadness called desire.\" - Patti Smith",
  "\"I always did something I was a little not ready to do. I think that’s how you grow. When there’s that moment of, ‘Wow, I’m not really sure I can do this,’ and you push through those moments, that’s when you have a breakthrough.\" - Marissa Mayer",
  "\"Don’t think about your errors or failures; otherwise, you’ll never do a thing.\" - Bill Murray",
  "\"It is not true that people stop pursuing dreams because they grow old. They grow old because they stop pursuing dreams.\" - Gabriel García Márquez",
  "\"One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don’t throw it away.\" - Stephen Hawking",
  "\"We are what we repeatedly do. Excellence, then, is not an act, but a habit.\" - Aristotle",
  "\"Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.\" - Norman Vincent Peale",
  "\"If you can dream it, you can do it.\" - Walt Disney",
  "\"Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it. Pry the door open or, if need be, wedge your foot in that door and keep it open.\" - Pauline Kael",
  "\"Do not wait; the time will never be ‘just right.’ Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.\" - George Herbert",
  "\"Aim for the moon. If you miss, you may hit a star.\" - W. Clement Stone",
  "\"Don’t watch the clock; do what it does. Keep going.\" - Sam Levenson",
  "\"There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.\" - Michael Phelps",
  "\"Keep your eyes on the stars, and your feet on the ground.\" - Theodore Roosevelt",
  "\"One way to keep momentum going is to have constantly greater goals.\" - Michael Korda",
  "\"Change your life today. Don’t gamble on the future, act now, without delay.\" - Simone de Beauvoir",
  "\"You just can’t beat the person who never gives up.\" - Babe Ruth",
  "\"Start where you are. Use what you have. Do what you can.\" - Arthur Ashe",
  "\"Why should you continue going after your dreams? Because seeing the look on the faces of the people who said you couldn’t… will be priceless.\" - Kevin Ngo",
]

# Uncomment the line below for the number of quotes when you run this file in the terminal
# print(len(quotes))

quote_select = random.choice(quotes)
print('\x1b[6;30;42m' + quote_select + '\x1b[0m')